[package]
name = "bench"
version = "0.1.0"
authors = ["Richard Apodaca <rich.apodaca@gmail.com>"]
edition = "2018"

[dependencies]

slice = { package = "gamma", version = "0.8.1" }
iter = {package = "gamma", version = "0.9.0" } 